/*
The following program implements various cryptographical functions.

The program will take an input message to be operated on  inputMessage  and output
the modified message  outputMessage  dependent on the function chosen.

All input is taken through the file  input.txt and all output is sent to the file  output.txt

The program has 5 different modes:
  1: Encryption using a Caesar (rotation) cipher
  2: Decryption using a Caesar (rotation) cipher with key known
  3: Encryption using a substitution cipher
  4: Decryption using a substitution cipher with key known
  5: Decryption using a substitution cipher with key NOT known

  NOTE: Mode 5 can be used for decryption using a Caesar cipher with key not known.

The user will select functionality by entering a mode, message, and key
(except for mode 5, in which case key should be left blank) into the input.txt file.
Mode should be either a single integer 1-5 when using a Caesar cipher, or a string of 26 unique letters
when using a substitution cipher. Mode and message should be entered directly after the template for each and key
should be input directly after the # character. The encrypted or decrypted message will be output to the
output.txt file.

  NOTE: Input message CANNOT be longer than 1000 characters.

NB: Possible errors with malloc when compiled using dcc. gcc used for compiling throughout writing of code.
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define KEYMAX 27
#define INPUTMAX 1001

char *caesarEncrypt(char inputMessage[], int key);
char *caesarDecrypt(char inputMessage[], int key);
char *substitutionEncrypt(char inputMessage[], char key[]);
char *substitutionDecrypt(char inputMessage[], char key[]);
char *frequencyAnalysisDecryption(char inputMessage[]);

int main() {

  int mode; // selection of functionality, 1-5
  char inputMessage[INPUTMAX]; // message length cannot exceed 1000 characters
  int caesarKey; // value between 0-26 to rotate alphabet by
  char substitutionKey[KEYMAX]; // key cannot exceed 26 characters

// FILE INPUT
//
  FILE *fp; // creates file pointer

  fp = fopen("input.txt", "r"); //opens input file for reading
  if(fp != NULL) { // error check for missing file, locked file, no permissions, etc.

// mode input from file
    fseek(fp, 11, SEEK_SET); // moves file pointer position to after mode input instruction
    fscanf(fp, "%d", &mode); // gets mode character from input file and stores in mode

    if (mode < 1 || mode > 5) { // error check for mode input

      printf("Invalid mode was entered. Please enter a mode between 1 and 5.\n");
      return 0; // exits program

    }

// message input from file
    fseek(fp, 22, SEEK_CUR); // moves file pointer position to after message input instruction
    fgets(inputMessage, INPUTMAX-1, fp); // gets message from input file and stores in inputMessage

    fseek(fp, 13, SEEK_CUR); // moves file pointer position to after key input instruction

// key input from file
    if (mode == 1 || mode == 2) { // true if Caesar cipher mode was chosen

      fscanf(fp, "%d", &caesarKey); // gets key from input file and stores in caesarKey

      if (caesarKey < 1 || caesarKey > 26) { // error check for caesarKey input

        printf("Invalid key entered. Please enter a key between 1 and 26.\n");
        return 0; // exits program

      }

    } else if (mode == 3 || mode == 4) { // true if substitution cipher mode was chosen

      fgets(substitutionKey, KEYMAX, fp); // gets key from input file and stores in substitutionKey

    } else { // true if decryption without known key was chosen

      for(int i = 0; i < 26; i++) { // loops through substitutionKey and replaces each element with testKey generated by frequency analysis

         substitutionKey[i] = frequencyAnalysisDecryption(inputMessage)[i];

      }

    }

  } else {

      printf("Could not open input.txt. Program exited.\n");
      return 0; // if file error triggered, exit program

  }

  fclose(fp); // closes input.txt

/*
!! Program function selection !!
1 = Encryption with Caesar cipher
2 = Decryption with Caesar cipher
3 = Encryption with Substitution cipher
4 = Decryption with Substitution cipher
5 = Decryption with either cipher and NO key given
*/

  switch(mode) {

    case 1: { // Encryption with Caesar cipher

      fp = fopen("output.txt", "w"); // opens output.txt file for writing
      fprintf(fp, "Output message:\n"); // template
      fputs(caesarEncrypt(inputMessage, caesarKey), fp); // writes outputMessage into output.txt file
      fclose(fp); // closes output.txt file for writing

      fputs(caesarEncrypt(inputMessage, caesarKey), stdout); // prints outputMessage to console

      break;

    }

    case 2: { // Decryption with Caesar cipher

      fp = fopen("output.txt", "w"); // opens output.txt file for writing
      fprintf(fp, "Output message:\n"); // template
      fputs(caesarDecrypt(inputMessage, caesarKey), fp); // writes outputMessage into output.txt file
      fclose(fp); // closes output.txt file for writing

      fputs(caesarDecrypt(inputMessage, caesarKey), stdout); // prints outputMessage to console

      break;

    }

    case 3: { // Encryption with Substitution cipher

      fp = fopen("output.txt", "w"); // opens output.txt file for writing
      fprintf(fp, "Output message:\n"); // template
      fputs(substitutionEncrypt(inputMessage, substitutionKey), fp); // writes outputMessage into output.txt file
      fclose(fp); // closes output.txt file for writing

      fputs(substitutionEncrypt(inputMessage, substitutionKey), stdout); // prints outputMessage to console

      break;

    }

    case 4: { // Decryption with Substitution cipher

      fp = fopen("output.txt", "w"); // opens output.txt file for writing
      fprintf(fp, "Output message:\n"); // template
      fputs(substitutionDecrypt(inputMessage, substitutionKey), fp); // writes outputMessage into output.txt file
      fclose(fp); // closes output.txt file for writing

      fputs(substitutionDecrypt(inputMessage, substitutionKey), stdout); // prints outputMessage to console

      break;

    }

    case 5: { // Decryption with Substitution cipher without key given

      fp = fopen("output.txt", "w"); // opens output.txt file for writing
      fprintf(fp, "Output message:\n"); // template
      fputs(substitutionDecrypt(inputMessage, frequencyAnalysisDecryption(inputMessage)), fp); // writes outputMessage into output.txt file
      fclose(fp); // closes output.txt file for writing

      fputs(substitutionDecrypt(inputMessage, frequencyAnalysisDecryption(inputMessage)), stdout); // prints outputMessage to console

      break;

    }

    default: {

      return 0; // error, program exits. should never trigger as only values 1-5 accepted for mode.

    }
  }

  return 0;

}

// FUNCTIONS
//

/*
Caesar Cipher Encryption
Function:     Encrypts a block of plain text using a Caesar (rotation) cipher.
              Each letter in the plain text is shifted by a certain amount of letters defined
              by the key value.
IO:           Takes plain text message to be encrypted  inputMessage  and encryption key  caesarKey
              and outputs encrypted message  outputMessage
Restrictions: inputMessage must be a string of characters with a maximum length of 1000.
              caesarKey must be a single integer such that 1 <= caesarKey <= 26.
*/

char *caesarEncrypt(char inputMessage[], int key) {

  char *outputMessage = malloc((strlen(inputMessage)+10) * sizeof(char)); // allocates block of memory for outputMessage equal to the size of the inputMessage string that can be accessed outside function

  for (int index = 0; inputMessage[index] != '\0'; index++) { // loops through message until null character is reached

    if ((int)inputMessage[index] <= 122 && (int)inputMessage[index] >= 97) { // true if element is an lower case letter

      inputMessage[index] -= 32; // Converts any lower case letters to upper case

    }

  // Converts each plain text char into a cipher text char in message
    if ((int)inputMessage[index] >= 65 && (int)inputMessage[index] <= 90) { // true if element is an upper case letter

      outputMessage[index] = ((int)inputMessage[index] - 65 + key) % 26 + 65;

    } else {

      outputMessage[index] = inputMessage[index];

    }

  }

  return outputMessage; //returns pointer to outputMessage array

}

/*
Caesar Cipher Decryption
Function:     Decrypts a block of cipher text using a Caesar (rotation) cipher.
              Each letter in the cipher text is shifted by a certain amount of letters defined
              by the key value.
IO:           Takes cipher text message to be decrypted  inputMessage  and decryption key  caesarKey
              and outputs decrypted message  outputMessage
Restrictions: inputMessage must be a string of characters with a maximum length of 1000.
              caesarKey must be a single integer such that 1 <= caesarKey <= 26.
*/

char *caesarDecrypt(char inputMessage[], int key) {

  char *outputMessage = malloc((strlen(inputMessage)+10) * sizeof(char)); // allocates block of memory for outputMessage equal to the size of the inputMessage string that can be accessed outside function

  for (int index = 0; inputMessage[index] != '\0'; index++) { // loops through message until null character is reached

    if ((int)inputMessage[index] <= 122 && (int)inputMessage[index] >= 97) { // true if element is an lower case letter

      inputMessage[index] -= 32; // Converts any lower case letters to upper case

    }

  // Converts each cipher text char in cipherText into a plain text char
    if ((int)inputMessage[index] >= 65 && (int)inputMessage[index] <= 90) { // true if element is an upper case letter

      outputMessage[index] = ((int)inputMessage[index] - 65 - key) % 26 + 65;

    } else {

      outputMessage[index] = inputMessage[index]; // If char not an upper case letter, ignore and print

    }
  }

  return outputMessage; //returns pointer to outputMessage array

}

/*
Substitution Cipher Encryption
Function:     Encrypts a block of plain text using a substitution cipher.
              Each letter in the plain text is replaced by a specific unique letter defined by
              the same index in the key.
IO:           Takes plain text message to be encrypted  inputMessage  and encryption key  substitutionKey
              and outputs encrypted message  outputMessage
Restrictions: inputMessage must be a string of characters with a maximum length of 1000.
              substitutionKey must be a string of exactly 26 unique upper case letters.
*/

char *substitutionEncrypt(char inputMessage[], char key[]){

  char *outputMessage = malloc((strlen(inputMessage)+10) * sizeof(char)); // allocates block of memory for outputMessage equal to the size of the inputMessage string that can be accessed outside function

  for(int i = 0; inputMessage[i] != '\0'; i++){ // loops through message until null character is reached

    if ((int)inputMessage[i] <= 122 && (int)inputMessage[i] >= 97) { // true if element is an lower case letter

      inputMessage[i] -= 32; // Converts any lower case letters to upper case

    }

    if ((int)inputMessage[i] >= 65 && (int)inputMessage[i] <= 90) { // true if element is an upper case letter

      outputMessage[i] = key[inputMessage[i] - 65]; // Converts each cipher text char in cipherText into a plain text char

    } else {

      outputMessage[i] = inputMessage[i]; // If char not an upper case letter, ignore and print

    }
  }

  return outputMessage; //returns pointer to outputMessage array

}

/*
Substitution Cipher Decryption
Function:     Decrypts a block of cipher text using a substitution cipher.
              Each letter in the cipher text is replaced by a specific unique letter defined by
              the same index in the key.
IO:           Takes cipher text message to be decrypted  inputMessage  and decryption key  substitutionKey
              and outputs decrypted message  outputMessage
Restrictions: inputMessage must be a string of characters with a maximum length of 1000.
              substitutionKey must be a string of exactly 26 unique upper case letters.
*/

char *substitutionDecrypt(char inputMessage[], char key[]){

  char *outputMessage = malloc((strlen(inputMessage)+10) * sizeof(char)); // allocates block of memory for outputMessage equal to the size of the inputMessage string that can be accessed outside function


  for(int i = 0; inputMessage[i] != '\0'; i++){ // Loops over each character in the encrypted message


    if ((int)inputMessage[i] <= 122 && (int)inputMessage[i] >= 97) { // If letter is lowercase -> convert to upper case (not necessary when decrypting)

      inputMessage[i] -= 32;

    }

    // Matches
    if ((int)inputMessage[i] >= 65 && (int)inputMessage[i] <= 90) { // true if element is an upper case letter

      for(int n = 0; n < 26; n++) {

        if(inputMessage[i] == key[n]){ // true if input letter matches nth letter in key

          outputMessage[i] = n + 65; // output letter at index i set to nth letter of alphabet (add 65 for ascii value of nth letter)

        }
      }
    } else {

      outputMessage[i] = inputMessage[i]; // do not modify letter

    }
  }

  return outputMessage; //returns pointer to outputMessage array

}

/*
Frequency Analysis Decryption
Function:     Attempts to decrypt a block of cipher text using frequency analysis to generate a substitution key.
              Each letter in the cipher text is replaced by a specific unique letter defined by
              the same index in the key.
IO:           Takes cipher text message to be decrypted  inputMessage and outputs decrypted message  outputMessage
Restrictions: inputMessage must be a string of characters with a maximum length of 1000.
*/

char *frequencyAnalysisDecryption(char *inputMessage) { // Returns frequency of each letter in inputMessage in alphabetical order

  int maxFreq; // frequency of most frequent letter so far
  char maxLetter; // letter with highest frequency
  char alphabet[KEYMAX] = {"ABCDEFGHIJKLMNOPQRSTUVWXYZ"}; // alphabet
  char stdFreqDistrib[KEYMAX] = {"ETAOINSHRDLCUMWFGYPBVKJXQZ"}; // standard frequency distribution for english letters
  int frequency[KEYMAX] = {}; // Frequency array of letters in string
  char *testKey = malloc(KEYMAX * sizeof(char)); // possible key to be altered from frequency analysis
                                                              // allocates block of memory for testKey equal to the key length that can be accessed outside function
  int len = strlen(inputMessage); // Gets length of string

// counts frequency of each letter in inputMessage
  for(int index = 0; index < len; index++) { // Loops through each letter in the string (previously used != '\0')

    for(int letter = 65; letter <= 90; letter++) { // Loops through each letter of the alphabet

      int inputChar = (int)inputMessage[index]; // Sets inputChar to inputMessage letter at index

      if(letter == inputChar) { // If the letters match, correct letter identified

        frequency[inputChar - 65]++; //  frequency of said letter +1
        break;

      }
    }
  }

// SORTING
  for(int n = 0; n <= 25; n++) { //n=0 is most freq, n=1 second most freq, etc...

    maxFreq = 0; // initialised maximum to 0, so that next letter will be max regardless of amount

    for(int i = 0; i <= 25; i++) { // finds letter of string with greatest frequency

      if(frequency[i] > maxFreq) { // if current letter has greater frequency than prev, replace

        maxFreq = frequency[i];
        maxLetter = i + 65; // converts into ASCII value for upper case letters

      }
    }


    for(int x = 0; x <= 25; x++) { // (loops alphabet) finds position of maxLetter in alphabet and sets maxLetter to same position in testKey

      if(alphabet[x] == stdFreqDistrib[n]) { // if true then nth most frequent letter correctly identified

        testKey[x] = maxLetter; // current most frequent letter placed in testKey at correct position
        break;

      }
    }

    frequency[maxLetter - 65] = 0; //sets the most frequent letter's frequency to 0 to find 2nd most frequent
  }


  return testKey; // returns pointer to testKey array

}
